/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package AnalizadorLexico;


/**
 *
 * @author fabri
 */
public enum Tokens {
    PALABRA_RESERVADA_CLA,
    PALABRA_RESERVADA_NUE,
    PALABRA_RESERVADA_EST,
    PALABRA_RESERVADA_PUB,
    PALABRA_RESERVADA_PRI,
    PALABRA_RESERVADA_SI,
    PALABRA_RESERVADA_SIN,
    PALABRA_RESERVADA_SEG,
    PALABRA_RESERVADA_CAS,
    PALABRA_RESERVADA_SAL,
    PALABRA_RESERVADA_PAR,
    PALABRA_RESERVADA_MIE,
    PALABRA_RESERVADA_HAC,
    PALABRA_RESERVADA_VER,
    PALABRA_RESERVADA_FAL,
    PALABRA_RESERVADA_FUN,
    PALABRA_RESERVADA_RET,
    PALABRA_RESERVADA_IMP,
    PALABRA_RESERVADA_ENT,
    PALABRA_RESERVADA_REA,
    PALABRA_RESERVADA_CAR,
    PALABRA_RESERVADA_CAD,
    PALABRA_RESERVADA_BOO,
    PALABRA_RESERVADA_NUL,
    PALABRA_RESERVADA_VAC,
    PALABRA_RESERVADA_PRIN,
    
    
    
    PUNTO_COMA,
    OPERADOR_SUMA,
    OPERADOR_RESTA,
    OPERADOR_MULTIPLICAR,
    OPERADOR_DIVISION,
    OPERADOR_MODULO,
    ASIGNACION,
    PUNTO,LLAVE_ABRE,
    LLAVE_CIERRA,
    PARENTESIS_ABRE, 
    PARENTESIS_CIERRA,
    CORCHETE_ABRE,
    CORCHETE_CIERRA,
    IDENTIFICADOR,
    TIPO_CADENA,
    TIPO_CARACTER,
    INCREMENTO,
    DECREMENTO,INC_VARIABLE,DEC_VARIABLE, MUL_VARIABLE, DIV_VARIABLE,IGUAL,DIFERENTE,MENOR,MENOR_IGUAL,MAYOR, MAYOR_IGUAL, AND,OR,NEGAR,
    NUMERO_ENTERO,
    NUMERO_REAL,
    ERROR,
    FX
}
